#    widget_generator.py
#    ────────────────────────────────────────
"""
    Generador geckónico de widgets.

    Crea nombres normalizados para:
        - botones
        - diales
        - sliders

    y genera el código de un panel PyQt5 listo para usar.

    Usado por:
        GeckoLayoutMaker
"""
import sys
from datetime import datetime

print("WidgetGenerator module loaded")

class WidgetGenerator:
    def __init__(self, buttons=0, dials=0, sliders=0):
        self.buttons = buttons
        self.dials = dials
        self.sliders = sliders

    # -----------------------------------------------------
    def generate_button_names(self):

        return [f"btn_{i:02}" for i in range(1, self.buttons + 1)]

    # -----------------------------------------------------
    def generate_dial_names(self):

        return [f"dial_{i:02}" for i in range(1, self.dials + 1)]

    # -----------------------------------------------------
    def generate_slider_names(self):

        return [f"slider_{i:02}" for i in range(1, self.sliders + 1)]

    # -----------------------------------------------------
    def generate_all(self):

        return {
            "buttons": self.generate_button_names(),
            "dials": self.generate_dial_names(),
            "sliders": self.generate_slider_names(),
        }

    # -----------------------------------------------------
    def generate_python_panel(self, class_name="GeckoPanel"):

        widgets = self.generate_all()

        buttons = widgets["buttons"]
        dials = widgets["dials"]
        sliders = widgets["sliders"]

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

        code = []

        # HEADER
        code.append('"""')
        code.append(f"Generated by GeckoLayoutMaker")
        code.append(f"Generated at: {timestamp}")
        code.append("")
        code.append("Widgets:")
        code.append(f"Buttons: {len(buttons)}")
        code.append(f"Dials: {len(dials)}")
        code.append(f"Sliders: {len(sliders)}")
        code.append('"""')
        code.append("")

        code.append("from PyQt5.QtWidgets import *")
        code.append("")
        code.append("")
        code.append(f"class {class_name}(QWidget):")
        code.append("")
        code.append("    def __init__(self):")
        code.append("        super().__init__()")
        code.append("")
        code.append("        self._build_ui()")
        code.append("")

        code.append("    def _build_ui(self):")
        code.append("")
        code.append("        layout = QVBoxLayout()")
        code.append("")

        # BUTTONS

        for name in buttons:
            code.append(f"        self.{name} = QPushButton('{name}')")

        if buttons:
            code.append("")

        # DIALS

        for name in dials:
            code.append(f"        self.{name} = QDial()")

        if dials:
            code.append("")

        # SLIDERS

        for name in sliders:
            code.append(f"        self.{name} = QSlider()")

        code.append("")

        # ADD TO LAYOUT

        for name in buttons + dials + sliders:
            code.append(f"        layout.addWidget(self.{name})")

        code.append("")
        code.append("        self.setLayout(layout)")

        return "\n".join(code)
    

    # Hola nova soy yo... este es el EOF